# Generated by Django 4.1.7 on 2023-03-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('Last_name', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Phone_no', models.CharField(max_length=100)),
                ('DOB', models.DateField()),
                ('Address', models.TextField(max_length=100)),
                ('Gender', models.CharField(max_length=100)),
                ('Polio', models.CharField(default='Polio -IPV Vaccine', editable=False, max_length=100)),
                ('Prev_dose', models.CharField(max_length=100)),
                ('Appt_date', models.DateField()),
                ('Appt_time', models.TimeField()),
            ],
        ),
    ]
