# Generated by Django 4.1.7 on 2023-03-13 10:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Accountsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_data',
            name='doctor_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient_data',
            name='spec',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient_data',
            name='Email',
            field=models.EmailField(max_length=100),
        ),
    ]
