# Generated by Django 4.1.7 on 2023-03-13 10:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Accountsapp', '0002_patient_data_doctor_name_patient_data_spec_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_data',
            name='BLOOD_TYPE',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
