# Generated by Django 4.1.7 on 2023-03-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialize', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
