# Generated by Django 4.1.7 on 2023-03-20 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accountsapp', '0003_patient_data_blood_type'),
        ('Paediatric_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adate', models.DateField()),
                ('atime', models.TimeField()),
                ('adoctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Paediatric_app.doctors')),
                ('apatient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accountsapp.patient_data')),
            ],
        ),
    ]
