# Generated by Django 4.1.7 on 2023-03-20 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Paediatric_app', '0002_appointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
